"""Run the Policy × Dataset Matrix — generate a summary report.

Usage (report-only mode, reads existing reports):
    python scripts/run_policy_matrix.py \\
        --config configs/matrix/stage8_policy_dataset_matrix.yaml \\
        --mode report-only \\
        --output-dir outputs/matrix
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore[assignment]

PROJECT_ROOT = Path(__file__).resolve().parents[1]

SUMMARY_FILENAME = "stage8_matrix_summary"


def _load_json(path: str) -> Optional[Dict[str, Any]]:
    p = Path(path)
    if p.exists():
        return json.loads(p.read_text(encoding="utf-8"))
    return None


def _status_icon(status: str) -> str:
    return {"full_benchmark": "✅", "smoke": "🟡", "feasibility": "🔍"}.get(status, "—")


def _get_metric(report: Optional[Dict], key: str) -> str:
    if report is None:
        return "—"
    # ActionChunk reports store metrics in chunk_metrics
    cm = report.get("chunk_metrics", {})
    if cm:
        if key == "mae":
            val = cm.get("mae_first")
        elif key == "rmse":
            val = cm.get("rmse_all")
        else:
            val = cm.get(key)
        if val is not None:
            return f"{val:.4f}"
    # Standard reports store metrics in raw_action_metrics
    m = report.get("raw_action_metrics", {})
    val = m.get(key)
    return f"{val:.4f}" if val is not None else "—"


def _get_target_info(report: Optional[Dict]) -> str:
    if report is None:
        return "—"
    return report.get("dataset", {}).get("target", {}).get("type", "action")


def run_matrix(
    config_path: str,
    mode: str = "report-only",
    output_dir: str = "outputs/matrix",
) -> Dict[str, Any]:
    if mode == "run-smoke":
        raise NotImplementedError(
            "run-smoke mode is planned but not implemented in Stage 8.4. "
            "Use --mode report-only to read existing reports."
        )

    if yaml is None:
        raise ImportError("PyYAML is required to read matrix config. pip install pyyaml")

    cfg = yaml.safe_load(Path(config_path).read_text(encoding="utf-8"))
    entries = cfg.get("matrix", [])

    rows: List[Dict[str, Any]] = []
    for entry in entries:
        dataset = entry.get("dataset", "?")
        policy = entry.get("policy", "?")
        status = entry.get("status", "?")
        report_path = entry.get("report", "")
        mode_entry = entry.get("mode", "report_only")

        report = _load_json(report_path) if report_path else None
        raw_mae = _get_metric(report, "mae")
        raw_rmse = _get_metric(report, "rmse")
        target_type = _get_target_info(report)

        rows.append({
            "dataset": dataset,
            "policy": policy,
            "status": status,
            "status_icon": _status_icon(status),
            "mode": mode_entry,
            "report_path": report_path,
            "report_exists": report is not None,
            "raw_mae": raw_mae,
            "raw_rmse": raw_rmse,
            "target_type": target_type,
        })

    # Build markdown summary
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    md_lines = [
        "# Stage 8 Policy × Dataset Matrix\n",
        "| Dataset | Policy | Status | Raw MAE | Raw RMSE | Target |",
        "|---|---|:---:|---:|---:|:---:|",
    ]
    for r in rows:
        md_lines.append(
            f"| {r['dataset']} | {r['policy']} "
            f"| {r['status_icon']} {r['status']} "
            f"| {r['raw_mae']} | {r['raw_rmse']} "
            f"| {r['target_type']} |"
        )

    md_lines.append("")
    md_lines.append("_Generated by run_policy_matrix.py_")

    summary = {
        "mode": mode,
        "num_entries": len(rows),
        "entries": rows,
        "markdown": "\n".join(md_lines),
    }

    # Write output files
    json_path = out_dir / f"{SUMMARY_FILENAME}.json"
    json_path.write_text(
        json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8",
    )
    print(f"Summary saved to {json_path}")

    md_path = out_dir / f"{SUMMARY_FILENAME}.md"
    md_path.write_text(summary["markdown"], encoding="utf-8")
    print(f"Markdown saved to {md_path}")

    # Print ASCII-safe summary (avoid UnicodeEncodeError on Windows GBK terminals)
    print(f"\nGenerated {len(rows)} matrix entries. Full summary at {json_path}")
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run the Policy × Dataset Matrix and generate summary."
    )
    parser.add_argument("--config", required=True, help="Matrix YAML config path")
    parser.add_argument("--mode", default="report-only", choices=["report-only", "run-smoke"],
                        help="Mode: report-only reads files, run-smoke also executes train/eval")
    parser.add_argument("--output-dir", default="outputs/matrix",
                        help="Output directory for summary files")
    args = parser.parse_args()

    run_matrix(
        config_path=args.config,
        mode=args.mode,
        output_dir=args.output_dir,
    )


if __name__ == "__main__":
    main()
